name: CD

on:
  push:
    tags: 'v*'

jobs:     
  release-linux:
    uses: Geode-solutions/actions/.github/workflows/cd-linux.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
    secrets: inherit

  release-linux-python:
    uses: Geode-solutions/actions/.github/workflows/cd-linux-python.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
    secrets: inherit

  release-windows:
    uses: Geode-solutions/actions/.github/workflows/cd-windows.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
      config: RelWithDebInfo
    secrets: inherit

  release-windows-python:
    uses: Geode-solutions/actions/.github/workflows/cd-windows-python.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
    secrets: inherit

  notify:
    uses: Geode-solutions/actions/.github/workflows/end-cd.yml@master
    needs: [release-linux, release-linux-python, release-windows, release-windows-python]
    secrets: inherit
