name: CI

on: 
  push:

jobs:
  format:
    uses: Geode-solutions/actions/.github/workflows/format.yml@master
    secrets: inherit
      
  build-linux:
    needs: format
    uses: Geode-solutions/actions/.github/workflows/ci-linux.yml@master
    with:
      repos: OpenGeode
    secrets: inherit

  build-linux-python:
    needs: format
    uses: Geode-solutions/actions/.github/workflows/ci-linux-python.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
    secrets: inherit

  coverage:
    needs: format
    uses: Geode-solutions/actions/.github/workflows/coverage.yml@master
    with:
      repos: OpenGeode
    secrets: inherit
  
  build-windows:
    needs: format
    uses: Geode-solutions/actions/.github/workflows/ci-windows.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
    secrets: inherit
        
  semantic-release:
    needs: [build-linux, build-linux-python, build-windows]
    uses: Geode-solutions/actions/.github/workflows/release.yml@master
    secrets: inherit
