name: CI

on: 
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  format:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - uses: Geode-solutions/actions/clang-format@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
  build-ubuntu:
    runs-on: ubuntu-18.04
    needs: format
    strategy:
      matrix:
        cc: [gcc, clang]
        cxx: [g++, clang++]
        config: [Debug, Release]
        exclude:
          - cc: gcc
            cxx: clang++
          - cc: clang
            cxx: g++

    steps:
    - uses: actions/checkout@v1
    - uses: Geode-solutions/actions/get-release@master
      id: opengeode
      with:
        repository: OpenGeode
        file: '-Linux.tar.gz'
        token: ${{ secrets.TOKEN }}
    - name: Compile
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_PREFIX_PATH:PATH=${{ steps.opengeode.outputs.path }} ..
        cmake --build . -- -j2
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
    - name: Test
      run: |
        mkdir -p test
        cd test
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_PREFIX_PATH:PATH="$GITHUB_WORKSPACE/build;$GITHUB_WORKSPACE/${{ steps.opengeode.outputs.path }}" ../tests
        cmake --build . -- -j2
        ctest --output-on-failure
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
    - name: Kcov
      run: curl -s https://raw.githubusercontent.com/Geode-solutions/actions/master/kcov.sh | bash -s -- ${GITHUB_WORKSPACE}/build/bin
      if: matrix.cc == 'gcc' && github.event_name == 'pull_request' && matrix.config == 'Debug'
    - uses: codecov/codecov-action@v1.0.2
      if: matrix.cc == 'gcc' && github.event_name == 'pull_request' && matrix.config == 'Debug'
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        file: kcov/kcov-merged/cobertura.xml
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CMK88TT4Z\",\"text\":\"Compilation or Testing failed for OpenGeode-Geosciences on Ubuntu\"}'        
      
  build-mac:
    runs-on: macOS-10.14
    needs: format
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v1
    - uses: Geode-solutions/actions/get-release@master
      id: opengeode
      with:
        repository: OpenGeode
        file: '-Darwin.tar.gz'
        token: ${{ secrets.TOKEN }}
    - name: Compile & Test
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_PREFIX_PATH:PATH=${{ steps.opengeode.outputs.path }} ..
        cmake --build .
        cd opengeode
        ctest --output-on-failure
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CLJ1PS7UN\",\"text\":\"Compilation or Testing failed for OpenGeode on macOS\"}'   

  build-mac-xcode:
    runs-on: macOS-10.14
    needs: format
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v1
    - name: Compile & Test
      run: |
        mkdir -p build
        cd build
        cmake -G "Xcode" -DCMAKE_PREFIX_PATH:PATH=${{ steps.opengeode.outputs.path }} ..
        cmake --build . --config ${{ matrix.config }}
        ctest -C ${{ matrix.config }} --output-on-failure
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CMK88TT4Z\",\"text\":\"Compilation or Testing failed for OpenGeode-Geosciences on macOS\"}' 

  build-windows:
    runs-on: windows-2016
    needs: format
    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v1
    - uses: Geode-solutions/actions/get-release@master
      id: opengeode
      with:
        repository: OpenGeode
        file: '-win64.zip'
        token: ${{ secrets.TOKEN }}
    - name: Compile & Test
      run: |
        mkdir -p build
        cd build
        cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH:PATH=${{ steps.opengeode.outputs.path }} ..
        cmake --build . --config ${{ matrix.config }}
        ctest -C ${{ matrix.config }} --output-on-failure
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"CMK88TT4Z\",\"text\":\"Compilation or Testing failed for OpenGeode-Geosciences on Windows\"}' 
        
  semantic-release:
    runs-on: ubuntu-18.04
    needs: [build-ubuntu, build-mac, build-mac-xcode, build-windows]
    steps:
    - uses: actions/checkout@v1
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
