name: Test

on:
  push:
    branches-ignore:
      - master
      - next

jobs:
  test:
    uses: Geode-solutions/actions/.github/workflows/cpp-test.yml@master
    with:
      name: OPENGEODE_GEOSCIENCES
      repos: OpenGeode
    secrets: inherit
